"""
team_3_simulation.py
======================
Team 3 - Simulation / Digital Twin agents.

Role in the pipeline:
-----------------------
Team 3 gives the lab a "digital twin" of its physical experiment: before (or
alongside) any real hardware run, a Python simulation script models the
expected behavior of the experiment, so the lab has a theoretical prediction
to compare real results against.

Two agents work together, in sequence, to produce a WORKING simulation:

  1. **PythonArchitect (Agent 3.1)** - the author. It reads the lab's global
     directive and current theory baseline, and asks the LLM to write a
     complete, self-contained Python script that simulates the experiment
     and writes its predicted results to `sim_data.csv`. This agent does
     NOT execute anything - its only job is producing `sim_script.py`.

  2. **SandboxDebugger (Agent 3.2)** - the isolated executor and fixer. It
     runs `sim_script.py` in a separate subprocess, captures stdout/stderr,
     and checks both the exit code AND whether `sim_data.csv` was actually
     produced. If either check fails, it feeds the exact captured traceback
     back to the LLM, asks for a corrected version of the FULL script,
     overwrites `sim_script.py`, and tries again - up to `MAX_DEBUG_RETRIES`
     times. If the script still isn't working after that, it raises
     `SimulationFailedException` rather than silently giving up or
     fabricating simulation data.

Why these are two separate agents rather than one:
-------------------------------------------------------
This mirrors a real software team: one role designs/writes the code, a
distinct role is responsible for actually running it and diagnosing
failures. Splitting them also matches this system's stateless,
single-responsibility agent design (see BaseAgent) - PythonArchitect's job
is complete and auditable the moment `sim_script.py` exists on disk;
SandboxDebugger's job is complete and auditable the moment `sim_script.py`
either runs successfully or is proven, after bounded retries, not to work.

Closing the feedback loop (Step 6):
---------------------------------------
`main_loop.py`'s Gatekeeper veto-retry loop (see its `_run_team_4_with_
veto_retry` and `_write_veto_feedback`) writes any veto reasoning to
`cycle_dir/A_Simulation/veto_feedback.md` before looping back to re-run
Team 3. `PythonArchitect` now actively reads that file (if present) and
injects it into its prompt as unmissable, CRITICAL context the new script
must explicitly address - without this, the retry loop would mechanically
re-invoke PythonArchitect up to 3 times while it kept regenerating a
similar simulation Gatekeeper had already rejected, never actually learning
from the rejection in between attempts.

A note on "sandboxing":
--------------------------
`SandboxDebugger` isolates execution at the PROCESS level (a separate
`subprocess`, its own stdout/stderr capture, and a hard wall-clock timeout)
and gives the script its own working directory. This is NOT a security
sandbox (no seccomp, no filesystem/network restriction, no resource-limited
container) - the generated script runs with the same OS-level privileges as
the rest of this application. That's an appropriate trade-off for scripts
generated by the same trusted LLM backend the rest of this system already
relies on for every other decision, but it is worth stating plainly rather
than implying a stronger isolation guarantee than actually exists.
"""

from __future__ import annotations

import json
import logging
import re
import subprocess
import sys
from pathlib import Path

from src import config
from src.base_agent import BaseAgent

logger = logging.getLogger(__name__)

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

# Filenames this pair of agents reads/writes within cycle_dir/A_Simulation/.
SIM_SCRIPT_FILENAME = "sim_script.py"
SIM_DATA_FILENAME = "sim_data.csv"

# Written by main_loop.py's Gatekeeper veto-retry loop
# (`_write_veto_feedback` in main_loop.py) whenever Gatekeeper (Team 4.3)
# vetoes a cycle and control loops back to Team 3 to tweak the simulation.
# PythonArchitect reads this file (if present) as CRITICAL feedback to
# incorporate - see `_read_veto_feedback` and `_build_script_prompt` below.
# Named identically to the constant `main_loop.py` writes to, since the two
# modules must agree on exactly where this file lives even though neither
# imports a shared constant from the other (main_loop.py owns the write
# path; this module owns the read path).
VETO_FEEDBACK_FILENAME = "veto_feedback.md"

# Maximum number of execute-and-fix attempts SandboxDebugger will make before
# giving up and raising SimulationFailedException. Bounded so a persistently
# broken script (or a persistently confused LLM) can never hang the pipeline
# in an unbounded retry loop.
MAX_DEBUG_RETRIES = 3

# Hard wall-clock ceiling on a single execution attempt. The generated script
# is arbitrary, LLM-authored code - without a timeout, a script that
# accidentally loops forever (e.g. a runaway `while True` in a naive
# numerical integrator) would hang this agent, and therefore the whole
# cycle, indefinitely. A timeout is treated exactly like any other failure:
# it's reported back to the LLM as the "error" to fix on the next attempt.
SUBPROCESS_TIMEOUT_SECONDS = 60

# Captured stdout/stderr can in principle be very large (e.g. a script that
# prints inside a loop before crashing). This caps how much of it we forward
# into the next fix-attempt prompt, keeping that prompt bounded regardless of
# how verbose a failing script's output gets.
MAX_OUTPUT_CHARS_IN_PROMPT = 3000


# --------------------------------------------------------------------------- #
# Exceptions
# --------------------------------------------------------------------------- #

class SimulationFailedException(Exception):
    """
    Raised by SandboxDebugger when the simulation script still fails to
    execute successfully (or still fails to produce sim_data.csv) after
    MAX_DEBUG_RETRIES execute-and-fix attempts.

    Carries the last attempt's captured output so the orchestration layer
    (or a human debugging logs) can see exactly how it failed on its final
    attempt, without needing to re-run anything.
    """

    def __init__(self, message: str, last_stdout: str, last_stderr: str, attempts: int):
        super().__init__(message)
        self.last_stdout = last_stdout
        self.last_stderr = last_stderr
        self.attempts = attempts


# --------------------------------------------------------------------------- #
# Shared helpers
# --------------------------------------------------------------------------- #

# Matches a fenced code block (```python ... ``` or plain ``` ... ```),
# capturing just the inner content. Generalizes the same technique
# llm_wrapper.py uses to strip JSON fences, applied here to Python code -
# LLMs frequently wrap code in markdown fences even when explicitly told not
# to, so we strip defensively rather than trusting prompt compliance alone.
_CODE_FENCE_PATTERN = re.compile(r"```(?:python)?\s*(.*?)\s*```", re.DOTALL | re.IGNORECASE)


def _strip_code_fences(text: str) -> str:
    """
    Strip a leading/trailing markdown code fence from an LLM's raw text
    response, if present, returning just the code inside. If no fence is
    found, the text is returned unchanged (on the assumption the model
    complied with the "no markdown" instruction and returned raw code).
    """
    text = text.strip()
    match = _CODE_FENCE_PATTERN.search(text)
    if match:
        return match.group(1).strip()
    return text


def _read_text_or_placeholder(path: Path, placeholder: str) -> str:
    """
    Read a file's text content, or return a descriptive placeholder if the
    file doesn't exist or is empty. Identical pattern to the one used in
    `Chef`, `MachinePlanner`, and `HypothesisArchitect` - kept as a
    module-level function here (rather than duplicated per-class) since both
    agents in this module are small and the helper is trivial.
    """
    if not path.exists():
        logger.warning("[team_3_simulation] Expected file missing: %s. Using placeholder text.", path)
        return placeholder

    text = path.read_text(encoding="utf-8").strip()
    return text if text else placeholder


def _truncate_for_prompt(text: str, max_chars: int = MAX_OUTPUT_CHARS_IN_PROMPT) -> str:
    """
    Bound how much captured stdout/stderr gets forwarded into a fix-attempt
    prompt. Truncates from the END and keeps the TAIL of the text rather
    than the head - for a traceback in particular, the actual error and
    exception message are almost always at the very end, so preserving the
    tail is what actually matters for the LLM to diagnose the failure.
    """
    if len(text) <= max_chars:
        return text
    omitted = len(text) - max_chars
    return f"...({omitted} earlier character(s) omitted)...\n{text[-max_chars:]}"


# --------------------------------------------------------------------------- #
# Agent 3.1: PythonArchitect
# --------------------------------------------------------------------------- #

class PythonArchitect(BaseAgent):
    """
    Reads the global directive and theory baseline, and asks the LLM to
    author a complete, self-contained Python simulation script modeling the
    experiment. Writes the result to `cycle_dir/A_Simulation/sim_script.py`.

    This agent never executes anything - authorship and execution are
    deliberately separate agents (see module docstring).

    Closing the feedback loop (Step 6): if `cycle_dir/A_Simulation/
    veto_feedback.md` exists - written by `main_loop.py` whenever Gatekeeper
    (Team 4.3) vetoes a cycle and control loops back here to tweak the
    simulation - this agent reads it and injects it into the prompt as
    CRITICAL feedback the new script must explicitly address. Without this,
    the veto-retry loop in `main_loop.py` would mechanically re-run
    PythonArchitect up to 3 times while it kept generating the same kind of
    simulation Gatekeeper already rejected, learning nothing from the
    rejection in between attempts.
    """

    def __init__(self, workspace_path: Path | None = None, model: str = config.OLLAMA_MODEL) -> None:
        super().__init__(agent_name="PythonArchitect", workspace_path=workspace_path, model=model)

    def run(self, cycle_dir: Path) -> None:
        """
        Single-pass entry point, invoked by `BaseAgent.execute()`.

        Flow:
            1. Read directive.md and theory_baseline.md, each with a
               graceful placeholder if missing/empty.
            2. Read A_Simulation/veto_feedback.md IF it exists - critical
               feedback from a prior Gatekeeper veto this cycle, if any
               (its absence is the normal case on a cycle's first attempt,
               so it's read silently, mirroring how Gatekeeper itself reads
               copilot_feedback.md).
            3. Ask the LLM to author a complete simulation script, with the
               veto feedback (if any) injected as a distinct, unmissable
               section of the prompt.
            4. Strip any markdown code fences and write the result to
               cycle_dir/A_Simulation/sim_script.py.
        """
        directive_text = _read_text_or_placeholder(
            config.DIRECTIVE_FILE, placeholder="(directive.md is empty - no directive has been set yet.)"
        )
        theory_text = _read_text_or_placeholder(
            config.THEORY_BASELINE_FILE,
            placeholder="(theory_baseline.md is empty - no prior theoretical grounding available yet.)",
        )
        veto_feedback_text = self._read_veto_feedback(cycle_dir)

        prompt = self._build_script_prompt(
            directive_text=directive_text, theory_text=theory_text, veto_feedback_text=veto_feedback_text
        )
        system_prompt = (
            "You are the Python Architect for an autonomous self-driving laboratory's digital "
            "twin. You write a single, complete, self-contained Python script that simulates "
            "the physical/chemical experiment described in the directive, grounded in the "
            "current theory baseline. Output ONLY raw Python code - no markdown code fences, "
            "no explanation before or after the code, nothing but the script itself. If a "
            "GATEKEEPER VETO FEEDBACK section is present in the prompt, it means an adversarial "
            "reviewer (the Gatekeeper) already rejected a previous attempt this cycle as not "
            "justifying a new physical experiment - your new script MUST explicitly address "
            "every concern raised there, not just repeat a similar simulation with minor "
            "cosmetic changes."
        )

        # response_model=None -> ask_llm returns the raw text response, not a
        # validated Pydantic object. A simulation script is source code, not
        # structured data, so there is no schema to validate it against here
        # - SandboxDebugger (Agent 3.2) is what actually validates it, by
        # running it.
        raw_response = self.ask_llm(prompt=prompt, system_prompt=system_prompt)
        assert isinstance(raw_response, str)

        script_code = _strip_code_fences(raw_response)

        simulation_dir = cycle_dir / "A_Simulation"
        simulation_dir.mkdir(parents=True, exist_ok=True)
        script_path = simulation_dir / SIM_SCRIPT_FILENAME
        script_path.write_text(script_code, encoding="utf-8")

        self.logger.info(
            "[PythonArchitect] Wrote simulation script (%d chars) to %s | veto_feedback_incorporated=%s",
            len(script_code),
            script_path,
            veto_feedback_text is not None,
        )

    def _read_veto_feedback(self, cycle_dir: Path) -> str | None:
        """
        Read `A_Simulation/veto_feedback.md` IF it exists, returning its raw
        content, or None if absent/empty.

        Returns `None` (rather than a placeholder string) specifically so
        `_build_script_prompt` can OMIT the entire feedback section on a
        normal, feedback-free first attempt - unlike every other
        "_read_text_or_placeholder"-style input in this codebase, injecting
        an explicit "(no feedback yet)" placeholder here would just be
        prompt clutter with zero informational value, since the common case
        (no veto has happened yet) doesn't need announcing.

        Its absence is completely normal (most cycles never get vetoed at
        all), so - mirroring Gatekeeper's identical treatment of
        `copilot_feedback.md` - this is read silently, with no warning log.
        """
        feedback_path = cycle_dir / "A_Simulation" / VETO_FEEDBACK_FILENAME
        if not feedback_path.exists():
            return None

        text = feedback_path.read_text(encoding="utf-8").strip()
        return text if text else None

    def _build_script_prompt(self, directive_text: str, theory_text: str, veto_feedback_text: str | None) -> str:
        """
        Assemble the full prompt: directive + theory baseline + (if present)
        Gatekeeper veto feedback, with explicit technical constraints the
        generated script must satisfy so it can actually run inside
        SandboxDebugger's subprocess.

        The veto feedback section, when present, is deliberately placed
        LAST - immediately before the technical requirements and task
        instructions - and marked as CRITICAL, so it's the freshest, most
        prominent thing in the model's context right before it starts
        generating code, rather than buried alongside the more static
        directive/theory context earlier in the prompt.
        """
        veto_feedback_block = ""
        if veto_feedback_text is not None:
            veto_feedback_block = f"""
⚠️ CRITICAL: Gatekeeper Veto Feedback (Red Team Rejection)

The Gatekeeper (an adversarial reviewer applying Occam's razor) has ALREADY REJECTED a
previous simulation attempt this cycle. This is not optional context - your new script MUST
explicitly address every concern raised below. Simply regenerating a similar simulation with
minor cosmetic changes will likely be rejected again.

{veto_feedback_text}
"""

        return f"""Write a Python simulation script (a "digital twin") for this laboratory's experiment.

Global Directive (directive.md)
{directive_text}

Current Theory Baseline (theory_baseline.md)
{theory_text}

{veto_feedback_block}

Technical requirements for the script

The script must be a single, complete, self-contained `.py` file that runs with
`python sim_script.py` and no command-line arguments.

Use ONLY the Python standard library (e.g. csv, math, random, statistics). Do NOT import
numpy, pandas, scipy, or any other third-party package - the sandbox execution
environment does not guarantee they are installed, and an ImportError will simply waste
a retry attempt.

The script MUST simulate the experiment as a TIME SERIES matching the hardware output
format. The output CSV (sim_data.csv) must have:
  - A first column representing time (e.g. "time_ms" or "time_s").
  - One column per observable the experiment produces. For this pH-sensitive
    fluorescence kinetics experiment, the columns are:
    "temp_c" (temperature in Celsius) and "fluorescence_raw_au" (raw fluorescence
    in arbitrary units).
  - At least 50 evenly-spaced time steps covering the full experiment duration.
  - Physically plausible curves: temperature should rise from ~22°C towards the
    target temperature with an exponential approach. Fluorescence should start at
    a higher value and decrease over time (pH drops, reducing fluorescein
    fluorescence). Do NOT produce random noise or static snapshots.
Do NOT produce a parameter sweep table, a lookup table of discrete trials, or
static end-state values. The simulation must model HOW the observables evolve
OVER TIME during the experiment.

The script MUST write its results to a file named exactly `sim_data.csv` in the current
working directory (do not construct an absolute path - just open("sim_data.csv", "w")),
with a header row and at least a few data rows.

The script must exit with code 0 on success. Wrap the main logic so that any unexpected
error still produces a clear traceback on stderr rather than hanging.

Output ONLY the raw Python source code - no markdown fences, no prose before or after it.
"""


# --------------------------------------------------------------------------- #
# Agent 3.2: SandboxDebugger
# --------------------------------------------------------------------------- #

class SandboxDebugger(BaseAgent):
    """
    Executes `cycle_dir/A_Simulation/sim_script.py` in an isolated
    subprocess, validates that it both exits successfully AND produces
    `sim_data.csv`, and - if it doesn't - feeds the captured output back to
    the LLM for a fix, overwrites the script, and retries. Raises
    `SimulationFailedException` if the script still isn't working after
    `MAX_DEBUG_RETRIES` attempts.
    """

    def __init__(self, workspace_path: Path | None = None, model: str = config.OLLAMA_MODEL) -> None:
        super().__init__(agent_name="SandboxDebugger", workspace_path=workspace_path, model=model)

    def run(self, cycle_dir: Path) -> None:
        """
        Single-pass entry point, invoked by `BaseAgent.execute()`.

        Flow (up to MAX_DEBUG_RETRIES times):
            1. Execute sim_script.py in a subprocess, capturing stdout/stderr
               and the exit code, bounded by SUBPROCESS_TIMEOUT_SECONDS.
            2. Check for success: exit code 0 AND sim_data.csv exists.
            3. On success: write shadow memory and return.
            4. On failure: if attempts remain, ask the LLM to fix the script
               (given the captured output) and overwrite sim_script.py, then
               retry. If attempts are exhausted, write shadow memory and
               raise SimulationFailedException.
        """
        simulation_dir = cycle_dir / "A_Simulation"
        simulation_dir.mkdir(parents=True, exist_ok=True)
        script_path = simulation_dir / SIM_SCRIPT_FILENAME

        if not script_path.exists():
            # An orchestration-level precondition failure, not a "the script
            # is broken" failure - PythonArchitect is expected to run before
            # this agent. Raised loudly rather than silently no-op'ing,
            # since silently proceeding would hide a real pipeline ordering
            # bug from whoever's debugging it.
            raise FileNotFoundError(
                f"No simulation script found at {script_path}. PythonArchitect must run "
                f"before SandboxDebugger."
            )

        attempts_log: list[dict] = []
        last_stdout = ""
        last_stderr = ""

        for attempt in range(1, MAX_DEBUG_RETRIES + 1):
            self.logger.info(
                "[SandboxDebugger] Executing %s (attempt %d/%d)...", script_path, attempt, MAX_DEBUG_RETRIES
            )
            execution_result = self._execute_script(script_path=script_path, simulation_dir=simulation_dir)
            last_stdout, last_stderr = execution_result["stdout"], execution_result["stderr"]

            success, failure_reason = self._check_success(
                returncode=execution_result["returncode"],
                timed_out=execution_result["timed_out"],
                simulation_dir=simulation_dir,
            )

            attempts_log.append(
                {
                    "attempt": attempt,
                    "returncode": execution_result["returncode"],
                    "timed_out": execution_result["timed_out"],
                    "success": success,
                    "stdout": last_stdout,
                    "stderr": last_stderr,
                }
            )

            if success:
                self.logger.info(
                    "[SandboxDebugger] Simulation succeeded on attempt %d/%d.", attempt, MAX_DEBUG_RETRIES
                )
                self._write_shadow_memory(cycle_dir=cycle_dir, attempts_log=attempts_log, final_success=True)
                return

            self.logger.warning(
                "[SandboxDebugger] Attempt %d/%d failed: %s", attempt, MAX_DEBUG_RETRIES, failure_reason
            )

            if attempt < MAX_DEBUG_RETRIES:
                fixed_code = self._request_fix(
                    script_path=script_path,
                    failure_reason=failure_reason,
                    stdout=last_stdout,
                    stderr=last_stderr,
                    attempt=attempt,
                )
                script_path.write_text(fixed_code, encoding="utf-8")
                self.logger.info(
                    "[SandboxDebugger] Wrote LLM-corrected script (%d chars) to %s for attempt %d.",
                    len(fixed_code),
                    script_path,
                    attempt + 1,
                )

        # Every attempt failed.
        self._write_shadow_memory(cycle_dir=cycle_dir, attempts_log=attempts_log, final_success=False)
        raise SimulationFailedException(
            message=(
                f"Simulation script at {script_path} failed to execute successfully and "
                f"produce {SIM_DATA_FILENAME} after {MAX_DEBUG_RETRIES} attempts."
            ),
            last_stdout=last_stdout,
            last_stderr=last_stderr,
            attempts=MAX_DEBUG_RETRIES,
        )

    # ------------------------------------------------------------------ #
    # Execution
    # ------------------------------------------------------------------ #

    def _execute_script(self, script_path: Path, simulation_dir: Path) -> dict:
        """
        Run `sim_script.py` in a subprocess using the SAME Python interpreter
        this application itself runs under (`sys.executable`), with its
        working directory set to `simulation_dir` so the script's relative
        `open("sim_data.csv", "w")` lands in the right place without the
        generated code needing to know anything about this project's
        directory layout.

        Returns a dict with keys: stdout, stderr, returncode, timed_out.
        A timeout is represented as returncode=None, timed_out=True, with
        whatever partial output subprocess captured before the timeout fired
        (if any) folded into stderr as an explicit note - it is treated
        exactly like any other failure by `_check_success`.
        """
        try:
            completed = subprocess.run(
                [sys.executable, str(script_path)],
                cwd=str(simulation_dir),
                capture_output=True,
                text=True,
                timeout=SUBPROCESS_TIMEOUT_SECONDS,
            )
            return {
                "stdout": completed.stdout,
                "stderr": completed.stderr,
                "returncode": completed.returncode,
                "timed_out": False,
            }
        except subprocess.TimeoutExpired as exc:
            partial_stdout = (
                exc.stdout.decode("utf-8", errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
            )
            partial_stderr = (
                exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
            )
            timeout_note = (
                f"\n[SandboxDebugger] Execution timed out after {SUBPROCESS_TIMEOUT_SECONDS}s and was "
                f"terminated. This usually means the script has an infinite loop or is otherwise "
                f"non-terminating - review any loops/convergence conditions.\n"
            )
            return {
                "stdout": partial_stdout,
                "stderr": partial_stderr + timeout_note,
                "returncode": None,
                "timed_out": True,
            }

    def _check_success(self, returncode: int | None, timed_out: bool, simulation_dir: Path) -> tuple[bool, str]:
        """
        Determine whether an execution attempt counts as a success, per two
        independent criteria that BOTH must hold:
            1. The process exited with code 0 (and did not time out).
            2. sim_data.csv actually exists in simulation_dir afterward.

        Checking (2) in addition to (1) matters because a script can exit
        cleanly (code 0) without ever having written its output - e.g. an
        early, unconditional `return`/`sys.exit(0)` before reaching the
        file-writing logic, or writing to the wrong filename. Treating that
        as "success" would silently leave the cycle without simulation data
        while reporting no error at all.

        Returns (success, failure_reason) - failure_reason is a human-readable
        explanation used both in logs and in the next fix-attempt prompt;
        it's empty when success is True.
        """
        if timed_out:
            return False, f"Execution timed out after {SUBPROCESS_TIMEOUT_SECONDS} seconds."

        if returncode != 0:
            return False, f"Script exited with non-zero status code {returncode}."

        sim_data_path = simulation_dir / SIM_DATA_FILENAME
        if not sim_data_path.exists():
            return False, (
                f"Script exited successfully (code 0) but did not produce the expected "
                f"{SIM_DATA_FILENAME} file in {simulation_dir}."
            )

        return True, ""

    # ------------------------------------------------------------------ #
    # LLM-driven fix
    # ------------------------------------------------------------------ #

    def _request_fix(
        self,
        script_path: Path,
        failure_reason: str,
        stdout: str,
        stderr: str,
        attempt: int,
    ) -> str:
        """
        Ask the LLM to produce a corrected version of the FULL script, given
        the exact failure just observed. The current (broken) script content
        is included verbatim so the model is fixing the actual code that
        just ran, not guessing at what might have been generated.
        """
        current_code = script_path.read_text(encoding="utf-8")

        prompt = f"""The following Python simulation script failed on execution attempt {attempt}. Fix it.

## Current Script (sim_script.py)
```python
{current_code}
```

## Failure Reason
{failure_reason}

## Captured stdout
```
{_truncate_for_prompt(stdout) if stdout.strip() else "(empty)"}
```

## Captured stderr
```
{_truncate_for_prompt(stderr) if stderr.strip() else "(empty)"}
```

## Your task
Diagnose the exact cause of the failure from the traceback/output above and return a
CORRECTED, COMPLETE version of the full script that fixes it. Remember: standard library
only (no numpy/pandas/scipy), must write its results to `sim_data.csv` in the current
working directory, and must exit with code 0 on success. Output ONLY the raw corrected
Python source code - no markdown fences, no explanation.
"""
        system_prompt = (
            "You are a meticulous Python debugging specialist fixing a broken simulation "
            "script for an autonomous self-driving laboratory's digital twin. You are given "
            "the exact script that just failed along with its captured output. Diagnose the "
            "root cause precisely and return a complete, corrected replacement for the "
            "entire script - not a diff or a snippet."
        )

        raw_response = self.ask_llm(prompt=prompt, system_prompt=system_prompt)
        assert isinstance(raw_response, str)
        return _strip_code_fences(raw_response)

    # ------------------------------------------------------------------ #
    # Shadow memory persistence
    # ------------------------------------------------------------------ #

    def _write_shadow_memory(self, cycle_dir: Path, attempts_log: list[dict], final_success: bool) -> None:
        """
        Persist every execution attempt (return code, timeout flag, full
        stdout/stderr, and whether it succeeded) as the complete audit trail
        for this agent's work on this cycle - useful for reviewing exactly
        what went wrong and how many attempts it took, without needing to
        re-run the script or the LLM.
        """
        shadow_dir = cycle_dir / "D_Shadow_Memory"
        shadow_dir.mkdir(parents=True, exist_ok=True)

        shadow_record = {
            "agent_name": self.agent_name,
            "model": self.model,
            "max_debug_retries": MAX_DEBUG_RETRIES,
            "final_success": final_success,
            "attempts": attempts_log,
        }

        shadow_path = shadow_dir / "sandbox_debugger_shadow.json"
        shadow_path.write_text(json.dumps(shadow_record, indent=2), encoding="utf-8")
        self.logger.info("[SandboxDebugger] Wrote shadow memory to %s", shadow_path)
