"""
workspace_manager.py
=====================
Owns the creation and integrity of the on-disk "shared brain" workspace that all
agents in the Self-Driving Lab read from and write to.

Because every agent process is stateless, the workspace itself IS the system's
memory. This module is deliberately conservative:

  * It NEVER overwrites a file that already exists (idempotency + we must never
    clobber another agent's work just because setup ran again) - INCLUDING an
    existing file that happens to be empty. If a file is already present on
    disk, whatever content (or lack of it) it has is left exactly as-is.
  * It only ever CREATES missing directories/files with sane defaults.
  * It is safe to call `initialize()` at the top of every single agent script,
    every single cycle, with zero risk of data loss.

Required layout (per spec):
----------------------------
    /workspace/00_System/
        directive.md            (empty)
        hardware_limits.yaml    (dummy min/max values - see DEFAULT_HARDWARE_LIMITS_YAML)
        summary.md              (empty)
    /workspace/01_Knowledge_Base/
        theory_baseline.md      (empty)
        Archive/
    /workspace/02_Research_Cycles/
    /workspace/03_Hardware_Queue/

`hardware_limits.yaml` is special-cased relative to the other three bootstrap
files: rather than a zero-byte placeholder, a MISSING hardware_limits.yaml is
populated with a real, working (if conservative/dummy) set of min/max safety
limits. This exists specifically so `SemanticSafetyAgent`
(`src/team_5_execution.py`) has an actual, non-empty limits file to validate
against from the very first cycle onward, rather than silently running with
zero safety enforcement until a human remembers to populate the file by hand.
An operator should still review and replace these dummy values with real,
hardware-verified limits before running against physical equipment - see the
warning comment embedded in DEFAULT_HARDWARE_LIMITS_YAML itself.
"""

from __future__ import annotations

import logging
from pathlib import Path

from src import config

logger = logging.getLogger(__name__)

# --------------------------------------------------------------------------- #
# Dummy default hardware safety limits
# --------------------------------------------------------------------------- #
# Written into hardware_limits.yaml ONLY when that file does not exist yet
# (see _create_hardware_limits_file below) - never overwrites an existing
# file, even an empty one, per this module's idempotency guarantee.
#
# These are placeholder values, not validated against any real hardware.
# Parameter names correspond to the fields SemanticSafetyAgent
# (src/team_5_execution.py) checks: the flat parameters object with
# mixing_speed_rpm, mixing_time_s, target_temperature_c, heating_time_s,
# measurement_interval_ms, fluorescence_duration_s, and reagents list with
# volume_ul and concentration_mm for each reagent. Any parameter without
# an entry here simply isn't safety-checked - see SemanticSafetyAgent's own
# docstring for that fail-safe behavior.
DEFAULT_HARDWARE_LIMITS_YAML = """\
# Hardware Limits for OrbusSim Dummy V2 (Fenton Reaction / Fluorescence Kinetics)
# Auto-generated by WorkspaceManager. REPLACE with real, hardware-verified
# values before running against physical equipment.

mixing_speed_rpm:
  min: 0
  max: 5000

mixing_time_s:
  min: 0.0
  max: 3600.0

target_temperature_c:
  min: 0.0
  max: 99.0

heating_time_s:
  min: 0.0
  max: 3600.0

measurement_interval_ms:
  min: 50
  max: 5000

fluorescence_duration_s:
  min: 5.0
  max: 600.0

reagent_volume_ul:
  min: 0.0
  max: 5000.0

reagent_concentration_mm:
  min: 0.0
  max: 200.0
"""


class WorkspaceManager:
    """
    Encapsulates all filesystem bootstrap logic for the shared agent workspace.

    Usage:
        wm = WorkspaceManager()
        wm.initialize()   # safe to call any number of times, from any process
    """

    def __init__(self, workspace_root: Path | None = None):
        # Allow dependency injection of a custom root (useful for unit tests /
        # running multiple isolated workspaces side by side). Defaults to the
        # single source of truth in config.py.
        self.workspace_root: Path = (workspace_root or config.WORKSPACE_ROOT).resolve()

        # Re-derive all subpaths relative to whichever root we ended up with,
        # rather than blindly trusting config's globals, so that a custom
        # workspace_root actually gets used consistently everywhere below.
        self.system_dir = self.workspace_root / "00_System"
        self.knowledge_base_dir = self.workspace_root / "01_Knowledge_Base"
        self.knowledge_base_archive_dir = self.knowledge_base_dir / "Archive"
        self.research_cycles_dir = self.workspace_root / "02_Research_Cycles"
        self.hardware_queue_dir = self.workspace_root / "03_Hardware_Queue"

        self.directive_file = self.system_dir / "directive.md"
        self.hardware_limits_file = self.system_dir / "hardware_limits.yaml"
        self.summary_file = self.system_dir / "summary.md"
        self.theory_baseline_file = self.knowledge_base_dir / "theory_baseline.md"

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def initialize(self) -> None:
        """
        Idempotently create the full workspace directory tree and bootstrap
        files. Safe to run on every agent startup / every research cycle.
        """
        logger.info("Initializing workspace at: %s", self.workspace_root)

        self._create_directories()
        self._create_empty_files()

        logger.info("Workspace initialization complete.")

    def is_initialized(self) -> bool:
        """
        Quick health check: True if every required directory and file already
        exists. Useful for agents that want to fail fast instead of silently
        auto-creating a workspace mid-run.
        """
        required_dirs = [
            self.workspace_root,
            self.system_dir,
            self.knowledge_base_dir,
            self.knowledge_base_archive_dir,
            self.research_cycles_dir,
            self.hardware_queue_dir,
        ]
        required_files = [
            self.directive_file,
            self.hardware_limits_file,
            self.summary_file,
            self.theory_baseline_file,
        ]
        return all(p.is_dir() for p in required_dirs) and all(p.is_file() for p in required_files)

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #

    def _create_directories(self) -> None:
        """
        Create every required directory. `mkdir(parents=True, exist_ok=True)`
        is inherently idempotent: it silently no-ops if the directory already
        exists, and creates any missing parent directories along the way.
        """
        directories = [
            self.workspace_root,
            self.system_dir,
            self.knowledge_base_dir,
            self.knowledge_base_archive_dir,
            self.research_cycles_dir,
            self.hardware_queue_dir,
        ]
        for directory in directories:
            directory.mkdir(parents=True, exist_ok=True)
            logger.debug("Ensured directory exists: %s", directory)

    def _create_empty_files(self) -> None:
        """
        Create each bootstrap file ONLY if it does not already exist.

        This is the crux of idempotency for files (mkdir's exist_ok covers
        directories, but files need an explicit existence check since we must
        never truncate/overwrite content another agent - or a human - may
        have already written, even if that content is empty).

        `hardware_limits_file` is handled separately (see
        `_create_hardware_limits_file`) since it gets real dummy content
        rather than a zero-byte placeholder; every other file here stays
        truly empty on first creation, since downstream agents/parsers
        already treat "empty file" as "not yet populated" for those.
        """
        empty_files = [
            self.directive_file,
            self.summary_file,
            self.theory_baseline_file,
        ]
        for file_path in empty_files:
            if not file_path.exists():
                # `touch()` creates a zero-byte file. We don't write any
                # placeholder content: downstream agents/parsers should treat
                # an empty file as "not yet populated", not as invalid input.
                file_path.touch()
                logger.debug("Created empty file: %s", file_path)
            else:
                logger.debug("File already exists, leaving untouched: %s", file_path)

        self._create_hardware_limits_file()

    def _create_hardware_limits_file(self) -> None:
        """
        Create `hardware_limits.yaml` with DEFAULT_HARDWARE_LIMITS_YAML's
        dummy min/max content, but ONLY if the file does not already exist.

        Kept as its own method (rather than folded into the empty_files loop
        above) because its bootstrap behavior is genuinely different: every
        other file in that loop gets `touch()`'d empty, while this one gets
        real starter content. Separating them keeps `_create_empty_files`'s
        name accurate for what it actually still does, and makes this file's
        special handling easy to find and reason about on its own.

        Per this module's idempotency guarantee, an EXISTING
        hardware_limits.yaml - even an empty one, e.g. from a workspace
        bootstrapped before this dummy-content behavior was added - is left
        completely untouched. We never overwrite a file a human or agent may
        have deliberately edited or emptied.
        """
        if not self.hardware_limits_file.exists():
            self.hardware_limits_file.write_text(DEFAULT_HARDWARE_LIMITS_YAML, encoding="utf-8")
            logger.info(
                "Created hardware_limits.yaml with dummy default limits at: %s. "
                "Review and replace with real, hardware-verified values before running "
                "against physical equipment.",
                self.hardware_limits_file,
            )
        else:
            logger.debug("File already exists, leaving untouched: %s", self.hardware_limits_file)


# ------------------------------------------------------------------------- #
# Allow `python -m src.workspace_manager` to bootstrap the workspace directly,
# e.g. as a one-off setup step before agents start running.
# ------------------------------------------------------------------------- #
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

    manager = WorkspaceManager()
    manager.initialize()

    print(f"Workspace ready at: {manager.workspace_root}")
    print(f"is_initialized() -> {manager.is_initialized()}")
